- hosts: appservers-php
  vars:
    - mysql_root_password: "07072110"
    - domain: "example.com"
    - download_url: "http://wordpress.org/latest.tar.gz"
    - wpdirectory: "/var/www"
    - db_name: "azim_db"
    - db_user: "azim"
    - db_password: "07072110"
  roles:
  - { role: nginx }
  - { role: percona-mysql }
  - { role: memcached }
  - { role: php5 }
  - { role: wordpress }
